### ISSUE TITLE
Add boats and signs support

### ISSUE THREAD

**Issue by saltyseadoggo** [DawnTeamMC/DawnAPI#11]
Cherry oak, palm and dark amaranth (from Wild Explorer) all lack boats and signs. I understand from other devs that these are difficult to implement in mods due to Minecraft's source code for them being difficult to work with, but, all the same, I would like to see them to complete these wood sets. Biome Makeover features boats and signs, Better Nether and Better End just signs, and Oh, the Biomes You'll Go just boats if you need a reference for how to implement them.

**Comment by Hugman76** [comment]
It has been on my TODO list for a while. I will try to see what I can do very soon!
