### ISSUE TITLE
Rename "NormalWoodBundle" to "OverworldWoodBundle"

### ISSUE THREAD

**Issue by YanisBft** [DawnTeamMC/DawnAPI#16]
It makes more sense and fits with NetherWoodBundle

**Comment by Dhranios** [comment]
Perhaps NonFlammable and Flammable instead, to match the data pack tags of vanilla?

**Comment by YanisBft** [comment]
Yeah it's actually better

**Comment by YanisBft** [comment]
Actually it's not, it's about fungus/saplings and not the flammability
