### ISSUE TITLE
Error adding to gradle project

### ISSUE THREAD

**Issue by Micalobia** [DawnTeamMC/DawnAPI#17]
When I add what was shown in the README to my gradle files, it gives this error report
https://pastebin.com/raw/QMGXHEgb

When adding this from OreVariants:
```java
repositories {
    maven { url 'https://maven.shedaniel.me/' }
    maven { url 'https://maven.terraformersmc.com/' }
}
```
It fixes itself. I'm not sure if it's intended for those to be required for users of the API or if it was just missed in the README

**Comment by YanisBft** [comment]
This is not intended

**Comment by YanisBft** [comment]
This was not resolved

**Comment by Hugman76** [comment]
I think that needs to be added to the README. I have medium understanding of the gradle technology, and I don't know if there's a way to automatically add the repository from a project that's added as a dependency.
