### ISSUE TITLE
You can suffocate in leaves

### ISSUE THREAD

**Issue by Noaaan** [DawnTeamMC/DawnAPI#20]
In contrast to vanilla and other modded leaves the ones created by Promenade counts as full blocks when standing inside them. This means when you are using a horse in any Promenade forest you will suffocate in the leaves instead of being able to pass through them.

![2021-08-19_19 46 52](https://user-images.githubusercontent.com/4163353/130118570-480f3b01-e4fe-45e2-8756-6a6704a8069c.png)

**Comment by Hugman76** [comment]
This is super weird. It actually is stated that leaves should never make players suffocate nor block the vision:
https://github.com/DawnTeamMC/DawnAPI/blob/4a111eced3d73cad2e1515775b1f3e845a8e77b8/src/main/java/com/hugman/dawn/api/util/DefaultBlockSettings.java#L15

**Comment by Hugman76** [comment]
Found the issue, it has something to do with the Fabric API: [Issue #1947 of Fabric API](https://github.com/FabricMC/fabric/issues/1947)

**Comment by Hugman76** [comment]
Ongoing PR for the fix: https://github.com/FabricMC/fabric/pull/1984
EDIT: now https://github.com/FabricMC/fabric/pull/2119

**Comment by Hugman76** [comment]
This bug got fixed in version 0.53.0 of the Fabric API.
