### ISSUE TITLE
Version 3.0.0 doesn't build on jitpack

### ISSUE THREAD

**Issue by n643064** [DawnTeamMC/DawnAPI#21]
[![](https://jitpack.io/v/DawnTeamMC/DawnAPI.svg)](https://jitpack.io/#DawnTeamMC/DawnAPI)
https://jitpack.io/com/github/DawnTeamMC/DawnAPI/v3.0.0/build.log

**Comment by Hugman76** [comment]
Yup, I know about this... will be fixed in the next version!
