### ISSUE TITLE
Not sure if this is Dawn or Promenade

### ISSUE THREAD

**Issue by Lozf** [DawnTeamMC/DawnAPI#25]
So, the game cannot make a new game- or recreate a game either, my crash report is here.  As I said, I'm not certain if it is Dawn or Promenade- with just Dawn there were some issues but it did not generate a crash report.
[crash-2022-03-29_09.31.29-client.txt](https://github.com/DawnTeamMC/DawnAPI/files/8373598/crash-2022-03-29_09.31.29-client.txt)
  Basically, it says something went wrong when trying to recreate a game and goes back to the menu, when I tried to make a new game it crashed.
Also, I did this with just Fabric API, cloth config, Dawn, and Promenade.

**Comment by Hugman76** [comment]
This is Promenade! See https://github.com/DawnTeamMC/Promenade/issues/70.
