### ISSUE TITLE
Mod conflict with Terrestria.

### ISSUE THREAD

**Issue by K0-RR** [DawnTeamMC/DawnAPI#3]
MC crashes when loading Dawn API and Terrestria mod.

Reported to TerraformersMC too - https://github.com/TerraformersMC/Terrestria/issues/193

crash report - doesn't generate
latest.log - https://hatebin.com/qhaywqqcpz
MultiMC log - https://hatebin.com/qwtbrpzwiu

**Comment by Hugman76** [comment]
### Thanks for the report!
This bug has been fixed in v1.5.2.
