### ISSUE TITLE
Block ID Issues when using on server

### ISSUE THREAD

**Issue by softsynth** [DawnTeamMC/DawnAPI#34]
### What happened?

When setting up a Fabric dependent server, installing Dawn API caused blocks to display improperly. I uninstalled all other mods to narrow it down to this one and made sure that the mod list between the client and server stayed identical to rule out client/server mismatch issues.

Below is a screenshot where Sunflower and Tall Grass blocks display as Prismarine Stairs.
![2023-04-23_19 23 15](https://user-images.githubusercontent.com/96661634/234105794-9f403dec-4070-405d-9a00-4f3ed81f40fd.png)

### Fabric API version

0.79.0+1.19.4

### Relevant log output

```shell
No warnings were displayed.
```

**Comment by Hugman76** [comment]
Yup, it's been already reported to me thrice in the past two weeks. I have absolutely no idea what is causing this.

**Comment by Hugman76** [comment]
This will be fixed with the Dawn API v4.2.1. Sorry about the huge delay on this issue.

**Comment by yukaling** [comment]
Question still exists on version 5.0.0   : (

**Comment by SimonSoIv** [comment]
yeah i have the same problem
![Screenshot 2023-07-29 154942](https://github.com/DawnTeamMC/DawnAPI/assets/86861750/807db1fc-d0da-4831-aceb-03c6d4b2f4b4)
![Screenshot 2023-07-29 155033](https://github.com/DawnTeamMC/DawnAPI/assets/86861750/7e802453-c236-422d-91e6-1a86d79561d4)

**Comment by SimonSoIv** [comment]
i found out that it was only happening on servers that didnt have dawn api in them so just remove them if you play on a different server ig

**Comment by Hugman76** [comment]
One of Dawn's dependencies make it so that you cannot play on a vanilla server with the mod installed on your client. This behavior is out of my control and to be honest isn't worth it.
If you wish to play on a vanilla server, don't play with my mods. 😅
If you wish to play on a modded server, make sure that you have installed the same mods as there.
