### ISSUE TITLE
Missmatching blocks on vanilla servers

### ISSUE THREAD

**Issue by kittech0** [DawnTeamMC/DawnAPI#37]
### What happened?

Basically the mod breaks blocks on vanilla servers.
This bug can be found in multiple mods like: traverse, dawn api, cinderscapes, blockus, terrestria

### Fabric API version

v5.0.0+1.20.1

**Comment by kittech0** [comment]
look at https://github.com/Brandcraf06/Blockus/issues/301

**Comment by KingALLO** [comment]
I also had this problem.

**Comment by JadeJuno** [comment]
This was already reported here. See #34

**Comment by Hugman76** [comment]
I don't intend people to play with my mods on servers... where my mods aren't installed.
This issue should be caused by something greater than the Dawn API, maybe at Fabric's level.
