### ISSUE TITLE
1.20.2 Support

### ISSUE THREAD

**Issue by user10072023github** [DawnTeamMC/DawnAPI#40]
### What is your idea about?

Hi guys, thanks for making this mod.  I standardized on 1.20.2 a ways back and don't want to move up until there's something really really compelling.  Will 1.20.2 support be added soon?  Thanks again

**Comment by Hugman76** [comment]
Sorry, I only update my mods to the latest versions of Minecraft

**Comment by user10072023github** [comment]
Very very very disappointing, but thanks for the reply
