### ISSUE TITLE
Invalid Configuration Property.

### ISSUE THREAD

**Issue by K0-RR** [DawnTeamMC/DawnAPI#8]
[Thread-263/WARN]: Dawn API (dawn): Invalid Configuration Property: projectID

**Comment by K0-RR** [comment]
Same for the newest NookBuild.

**Comment by Hugman76** [comment]
Where do you encounter this line?

**Comment by K0-RR** [comment]
The same message is still printing on v1.6.2.

**Comment by K0-RR** [comment]
> Where do you encounter this line?

In the log file when the game is launching.

**Comment by Hugman76** [comment]
### Thanks for the report!
This bug has been fixed for the next version.
